insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (1,'albert_park','Albert Park Grand Prix Circuit','Melbourne');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (2,'sepang','Sepang International Circuit','Kuala Lumpur');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (3,'bahrain','Bahrain International Circuit','Sakhir');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (4,'catalunya','Circuit de Barcelona-Catalunya','MontmelÃ³');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (5,'istanbul','Istanbul Park','Istanbul');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (6,'monaco','Circuit de Monaco','Monte-Carlo');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (7,'villeneuve','Circuit Gilles Villeneuve','Montreal');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (8,'magny_cours','Circuit de Nevers Magny-Cours','Magny Cours');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (9,'silverstone','Silverstone Circuit','Silverstone');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (10,'hockenheimring','Hockenheimring','Hockenheim');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (11,'hungaroring','Hungaroring','Budapest');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (12,'valencia','Valencia Street Circuit','Valencia');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (13,'spa','Circuit de Spa-Francorchamps','Spa');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (14,'monza','Autodromo Nazionale di Monza','Monza');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (15,'marina_bay','Marina Bay Street Circuit','Marina Bay');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (16,'fuji','Fuji Speedway','Oyama');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (17,'shanghai','Shanghai International Circuit','Shanghai');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (18,'interlagos','AutÃ³dromo JosÃ© Carlos Pace','SÃ£o Paulo');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (19,'indianapolis','Indianapolis Motor Speedway','Indianapolis');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (20,'nurburgring','NÃ¼rburgring','NÃ¼rburg');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (21,'imola','Autodromo Enzo e Dino Ferrari','Imola');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (22,'suzuka','Suzuka Circuit','Suzuka');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (23,'osterreichring','A1-Ring','Spielburg');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (24,'yas_marina','Yas Marina Circuit','Abu Dhabi');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (25,'galvez','AutÃ³dromo Juan y Oscar GÃ¡lvez','Buenos Aires');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (26,'jerez','Circuito de Jerez','Jerez de la Frontera');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (27,'estoril','AutÃ³dromo do Estoril','Estoril');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (28,'okayama','Okayama International Circuit','Okayama');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (29,'adelaide','Adelaide Street Circuit','Adelaide');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (30,'kyalami','Kyalami','Midrand');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (31,'donington','Donington Park','Castle Donington');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (32,'rodriguez','AutÃ³dromo Hermanos RodrÃ­guez','Mexico City');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (33,'phoenix','Phoenix street circuit','Phoenix');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (34,'ricard','Circuit Paul Ricard','Le Castellet');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (35,'yeongam','Korean International Circuit','Yeongam County');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (36,'jacarepagua','AutÃ³dromo Internacional Nelson Piquet','Rio de Janeiro');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (37,'detroit','Detroit Street Circuit','Detroit');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (38,'brands_hatch','Brands Hatch','Kent');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (39,'zandvoort','Circuit Park Zandvoort','Zandvoort');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (40,'zolder','Zolder','Heusden-Zolder');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (41,'dijon','Dijon-Prenois','Dijon');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (42,'dallas','Fair Park','Dallas');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (43,'long_beach','Long Beach','California');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (44,'las_vegas','Las Vegas Street Circuit','Nevada');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (45,'jarama','Jarama','Madrid');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (46,'watkins_glen','Watkins Glen','New York State');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (47,'anderstorp','Scandinavian Raceway','Anderstorp');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (48,'mosport','Mosport International Raceway','Ontario');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (49,'montjuic','MontjuÃ¯c','Barcelona');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (50,'nivelles','Nivelles-Baulers','Brussels');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (51,'charade','Charade Circuit','Clermont-Ferrand');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (52,'tremblant','Circuit Mont-Tremblant','Quebec');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (53,'essarts','Rouen-Les-Essarts','Rouen');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (54,'lemans','Le Mans','Le Mans');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (55,'reims','Reims-Gueux','Reims');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (56,'george','Prince George Circuit','Eastern Cape Province');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (57,'zeltweg','Zeltweg','Styria');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (58,'aintree','Aintree','Liverpool');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (59,'boavista','Circuito da Boavista','Oporto');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (60,'riverside','Riverside International Raceway','California');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (61,'avus','AVUS','Berlin');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (62,'monsanto','Monsanto Park Circuit','Lisbon');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (63,'sebring','Sebring International Raceway','Florida');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (64,'ain-diab','Ain Diab','Casablanca');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (65,'pescara','Pescara Circuit','Pescara');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (66,'bremgarten','Circuit Bremgarten','Bern');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (67,'pedralbes','Circuit de Pedralbes','Barcelona');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (68,'buddh','Buddh International Circuit','Uttar Pradesh');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (69,'americas','Circuit of the Americas','Austin');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (70,'red_bull_ring','Red Bull Ring','Spielburg');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (71,'sochi','Sochi Autodrom','Sochi');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (72,'port_imperial','Port Imperial Street Circuit','New Jersey');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (73,'BAK','Baku City Circuit','Baku');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (74,'hanoi','Hanoi Street Circuit','Hanoi');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (75,'portimao','AutÃ³dromo Internacional do Algarve','PortimÃ£o');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (76,'mugello','Autodromo Internazionale del Mugello','Mugello');
insert into D_CIRCUITO (id_circuito,rf_circuito,no_circuito,localizacao) values (77,'jeddah','Jeddah Street Circuit','Jeddah');
